spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nangman
    username: nangman
    password: your_local_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false